### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by Rido** [GregoryDosh/Home-Assistant-DreamScreen-Service#8]
Hi Gregory,

Great work, thanks! 

Today I tried to install the Dreamscreen service in my Hassbian environment but it won't work 😞 
Maybe you could add a step-by-step plan to install the HASS Dreamscreen service.

I have gone through the following steps:

1. `git clone git@github.com:GregoryDosh/Home-Assistant-DreamScreen-Service.git dreamscreen` in the **custom_component** directory
2. `pip3 install PyDreamScreen` with the homeassistant user on the Hassbian rpi.
3. Added the following code to **configuration.yaml**:
```
dreamscreen:
  ip_address: 192.168.2.156
```

The dreamscreen services are available but I don't have a Dreamscreen entity.

Am I doing something wrong?

Thanks!

**Comment by GregoryDosh** [comment]
I'm looking into making this a bit more robust and less finicky, along with better documentation soon.  I'm in the middle of a housing project that has left me without internet or a lot of normal resources so I've not been able to get anything done yet, and I apologize.

What you've got there seems like it should be working.  Do the logs reveal anything about the startup of the dreamscreen service?

**Comment by yashijoe** [comment]
Hello Gregory,
is the installation procedure still the same as by Rido post?
Thanks

**Comment by J3n50m4t** [comment]
@yashijoe yes, but you don't have to install pydreamscreen (on hassio at least - not sure about others)

checkout [Readme](https://github.com/GregoryDosh/Home-Assistant-DreamScreen-Service#configuration)
